### ISSUE TITLE
Failed to open TCP connection

### ISSUE THREAD

**Issue by juragandotid** [timrogers/lloydstsb#2]
I'm try running this script and i got an error : 

 Failed to open TCP connection to online.lloydstsb.co.uk:443 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for "online.lloydstsb.co.uk" port 443) (Errno::ETIMEDOUT)

Help me pleasee, Thank you :)

**Comment by timrogers** [comment]
This gem is very old and most likely won't work with banks' modern systems. Sorry 🙈  I'll add a notice to that effect to the readme when I get a chance.
